version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: onehr-db
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: onehr
      MYSQL_PASSWORD: onehr
      MYSQL_DATABASE: onehr
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uonehr -ponehr"]
      interval: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: onehr-redis
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    container_name: onehr-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - miniodata:/data

volumes:
  mysqldata:
  miniodata: